source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target "PunchUIScrollView" do
  pod "PunchScrollView", :path => "../PunchScrollView.podspec"
end

target "PunchUIScrollViewTests" do
  pod 'FBSnapshotTestCase'
  pod 'PunchScrollView', :path => "../PunchScrollView.podspec"
end
